name: Publish Package

on:
  release:
    types: [published]
    tags:
      - "v*.*.*"

jobs:
  deployment:
    # prevents this action from running on forks
    if: github.repository == 'CAKE-com/pumble-node-sdk'
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract release version
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Set node version to 16
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Prepare SDK
        run: cd pumble-sdk && npm install && npm run compile && cd ..

      - name: Prepare CLI
        run: cd pumble-cli && npm install && npm run compile && cd ..

      - name: Update Package Versions
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          version=${RELEASE_VERSION:1}
          echo 'Updating packages to version:' $version
          cat <<< "$(jq -M --arg version $version '.version=$version' ./pumble-cli/package.json)"  > ./pumble-cli/package.json
          cat <<< "$(jq -M --arg version $version '.version=$version' ./pumble-sdk/package.json)" > ./pumble-sdk/package.json
          cat <<< "$(jq -M --arg version $version '.devDependencies["pumble-cli"]=$version' ./pumble-cli/template/_package.json)" > ./pumble-cli/template/_package.json
          cat <<< "$(jq -M --arg version $version '.dependencies["pumble-sdk"]=$version' ./pumble-cli/template/_package.json)" > ./pumble-cli/template/_package.json
          echo 'CLI package.json'
          cat ./pumble-cli/package.json
          echo 'SDK package.json'
          cat ./pumble-sdk/package.json
          echo 'Template package.json'
          cat ./pumble-cli/template/_package.json

      - name: Publish SDK
        run: cd pumble-sdk && npm run publish && cd ..
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish CLI
        run: cd pumble-cli && npm run publish && cd ..
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
